### PR TITLE
Fix: We don't need to check for updates if we need the current installed version

### PR DESCRIPTION
**Pull request by p0psicles**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

This will speedup loading the /config page allot!

### CODE REVIEW

**Comment by fernandog** [comment]
Why not disabled "check for updates" setting?

**Comment by p0psicles** [comment]
Because that option has nothing to do with showing the version.
This is what's causing the slow page load:
image

**Comment by fernandog** [comment]
Approved

**Comment by OmgImAlexis** [comment]
Approved!

**Pull request merged**
