### PR TITLE
Fix Search settings tab

### PR DESCRIPTION
**Pull request by fernandog**
Fixes https://github.com/pymedusa/SickRage/issues/741

Fixes until "UI Cleanup" is merged

### CODE REVIEW

**Comment by p0psicles** [comment]
Can't we just add this to UI cleanup?

**Comment by fernandog** [comment]
@p0psicles labrys said he already fixed but until it gets merged... its a huge PR that will need a lot of testing.

**Comment by p0psicles** [comment]
Approved

**Comment by labrys** [comment]
Make sure you're adding milestones to PRs before merge.

**Pull request merged**
