### PR TITLE
Make ep wanted only after show finish airs

### PR DESCRIPTION
**Pull request by fernandog**
image

```
2016-02-24 00:46:33 INFO     DAILYSEARCHER :: New episode American Crime Story - S01E04 - 100% Not Guilty airs today, setting to default episode status for this show: Wanted
2016-02-23 23:46:31 INFO     DAILYSEARCHER :: New episode Marvel's Agent Carter - S02E09 - A Little Song and Dance airs today, setting to default episode status for this show: Wanted
2016-02-23 23:46:31 INFO     DAILYSEARCHER :: New episode Marvel's Agent Carter - S02E08 - The Edge of Mystery airs today, setting to default episode status for this show: Wanted
2016-02-23 22:46:28 INFO     DAILYSEARCHER :: New episode The Flash (2014) - S02E15 - King Shark airs today, setting to default episode status for this show: Wanted
```

### CODE REVIEW

**Comment by fernandog** [comment]
working as expected
@medariox @OmgImAlexis @labrys

**Comment by labrys** [comment]
Approved!
I haven't tested in person but the logic looks good.  One thing that may need tested is on windows since dateutils handling of timezone is currently spotty but our work around is mostly solid and dateutil is nearly finished with its fixes.

**Comment by labrys** [comment]
Also we might consider putting in a guard for an incorrect run time if we find it necessary.

**Comment by fernandog** [comment]
we already do:
datetime.timedelta(minutes=try_int(show.runtime, 60))

if not runtime, use 60 instead

**Comment by labrys** [comment]
I mean if run time = 600000 minutes for example.   Or run time = -300.  Those are still valid ints, but not really valid values.

**Comment by fernandog** [comment]
I see. I think we can check if runtime <= 90/120 (like double episodes)

@duramato ideias ? what about talk shows or else?

**Comment by duramato** [comment]
Just default to a runtine of 40 min since thats the average

**Pull request merged**
