### PR TITLE
Add web url global

### PR DESCRIPTION
**Pull request by p0psicles**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
@p0psicles concluded? If so will mergeso @OmgImAlexis can rebase his branch and test

**Comment by fernandog** [comment]
Approved

**Comment by fernandog** [comment]
@p0psicles what if user has ipv6 enabled?

**Comment by OmgImAlexis** [comment]
@fernandog it should be whatever url they connect to medusa with, for example if they're connecting via a nginx proxy with the domain as x.com, HTTPS enabled and the webroot of medusa it'll be `https://x.com/medusa/`.

@p0psicles is that how it is right now? Also do you know if that does actually take into account the proxy server if used?

**Comment by OmgImAlexis** [comment]
Approved.

**Pull request merged**
