### PR TITLE
Fix compact history results so that all actions for a release are shown

### PR DESCRIPTION
**Pull request by labrys**
...and limit it by number of releases, not number of actions
based on #171 by @fernandog

##### common.py
* Change splitCompositeStatus to return a namedtuple(status, quality)
* Optimize imports
* Minor clean-up

##### webapi.py
* Change to use the named tuples in history
* Optimize imports
* Remove unused variables
* Clean up todo items

##### webserve.py
* Move compact history subroutine from webserve.py sickrage\show\History
* Optimize imports
* Remove unused variables
* Remove redundant parentheses
* Clean up todo items

##### sickrage/show/History.py
* Rewrite compact history subroutine
  * Update show.history to use namedtuple instead of dict
  * return namedtuple instead of tuple
  * limit releases by number of releases and not number of actions
* Optimize imports
* Add todo and docs

### CODE REVIEW

**Comment by labrys** [comment]
@OmgImAlexis this has some change in the mako.  Also I moved the col width from the <td> to the <th> although it should probably just be moved to css.

**Comment by fernandog** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/pymedusa/SickRage/pull-request/223/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=pymedusa/SickRage)

**Comment by labrys** [comment]
Approved

**Comment by labrys** [comment]
@MGaetan89 this replaced #171, it shouldn't affect api results at all, but let me know if you have any concerns

**Pull request merged**
