### PR TITLE
Hide sensitive info from the logs

### PR DESCRIPTION
**Pull request by duramato**
Like ips/domains , api keys and tokens

### CODE REVIEW

**Comment by fernandog** [comment]
Approved

**Comment by labrys** [comment]
While I definitely understand a desire (and need) to censor these items I think excessive censoring can make some things difficult to debug.  Until we fix logging in general, how about a Paranoia setting?  It would replace the `True` value for the censor argument.

**Comment by fernandog** [comment]
@duramato @labrys added setting

**Comment by duramato** [comment]
needs to be added to all `censor_log`s

**Comment by labrys** [comment]
Sorry kinda forgot about this one, I'll try to find the time to test before this weekend.

**Comment by fernandog** [comment]
Not working.
I used kodi notifications and still host appear in log

**Comment by duramato** [comment]
The setting you made it disabled by default

**Comment by fernandog** [comment]
so? I enabled to test

**Comment by fernandog** [comment]
@duramato you should close it as no one seems interested

**Comment by labrys** [comment]
@fernandog No just some people like to put some thought into their code instead of rushing things.

**Comment by labrys** [comment]
A setting of `Normal` provides the same filters as previously.  `Low` filters only passwords/api keys/etc.  `Disabled` provides no filtering at all.  `High` adds the additional filters such as hosts.  Nothing is currently set to `Max`.  `Stupid` filters every single attribute from the config file.  @duramato I think you'll get a kick out of the `Absurd` level :grinning:

**Comment by labrys** [comment]
Approved.  Privacy levels are low, normal, high.

**Comment by labrys** [comment]
QC issues are pre-existing and will be addressed as part of the webserver and config file changes

**Pull request merged**
