### PR TITLE
Only snatch proper if we actually have a download, compare codec befo…

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

…re snatching

This fixes the situations where we have a PROPER downloaded before a non-PROPER and it keeps trying to PP until we manually delete the NON-PROPER.

Current flow:
Snatch (non-proper/proper) -> Found proper? -> Finished download? -> Download proper

Old flow:
Snatch (non-proper/proper) -> Found proper? -> Download proper

### CODE REVIEW

**Comment by fernandog** [comment]
so you prefer continue downloading the proper (if is on the client, wasting bandwidth and cpu), wait PP to kick-in, PP it, then wait FINDPROPERs to run, then snatch proper?

Today as soon we find a PROPER we snatch it. 

`This fixes the situations where we have a PROPER downloaded before a non-PROPER and it keeps trying to PP until we manually delete the NON-PROPER.`

If the problem is the non-proper being stucked in PP folder, just use my PR that removes the torrent from client OR from PP folder when 1) snatches a proper OR 2) manual snatch when medusa already snatched another*

* when user manual search one episode and snatched it. Then he manually snatch another. So he will have two releases from same ep in PP folder. OR one stucked in client (so that's why he manually snatched another release)

imo the best solution to files being stucked in PP folder is to remove then with my PR

**Comment by fernandog** [comment]
I bet whatever you want that you didn't test this PR =)
I doesn't work

**Comment by medariox** [comment]
Right now we can have multiple propers download at the same, this PR avoids it by downloading only one until the download is finished. If it isn't working, it will need to be fixed.

**Comment by fernandog** [comment]
If we do propers redownload is because its another PROPER:
non-proper > proper > real.proper

the only real issue about re-downloading proper is the one about `x265` and the one that @duramato said when torrentz2 is renaming torrent name:

```
Suits.6x09.(720p-HDTV-x264-REPACK-KILLERS)[VTV]   ->  Suits.S06E09.REPACK.720p.HDTV.x264-KILLERS 
```

@medariox Prove me I'm wrong showing logs of propers redownloads that are not in those two cases

**Comment by medariox** [comment]
I don't have to prove anything. Downloading a proper while another is already snatched is wrong. Using history that can be cleared any time, to make this kind of checks, is wrong.

**Comment by fernandog** [comment]
@medariox So you are fixing an issue that you can't prove?! lol

easy fix about history. so when snatching a file, in `release_name` column we add torrentname|nzbname so it won't be empty. so can ditch the history check

**Comment by fernandog** [comment]
` Downloading a proper while another is already snatched is wrong.`

wrong in your opinion. I'm my opinion it makes sense. that's why we FINDPROPERS. and that is how it works since forever

**Pull request closed without merging**
