### PR TITLE
reduced resolution and increased compression on default medusa poster

### PR DESCRIPTION
**Pull request by p0psicles**
We where loading 1,2M posters for each show, on first load.
Because the poster is not loaded as "static" content, it's loaded multiple times.

For ex: showPoster/?show=254559&which=poster_thumb loads the default poster for me.
If we can change this to for ex: images/default_poster.png, that would help installations with allot of shows that don't have poster loaded from indexer. But this is out of scope for the PR.

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

….png. Copied original poster to poster-large.png.

### CODE REVIEW

**Comment by fernandog** [comment]
Approved

**Comment by p0psicles** [comment]
@OmgImAlexis can you give me an approval and merge at the same time pls?

**Comment by OmgImAlexis** [comment]
@p0psicles if we can look into what supports svg files we might be able to just use that instead of an actual image. That'd cut down on it even more.

**Comment by p0psicles** [comment]
@OmgImAlexis: just checked http://caniuse.com/#feat=svg
But for example chrome 46 is not supported. And this is the version pushed by my company. Also IE8 will not be supported anymore. Although that's something I can live with.

**Comment by OmgImAlexis** [comment]
Not sure what you were looking at but all Chrome's are supported from 4 and up. Only Chrome version 26 has issues and we could detect IE8 if need be and replace it with a png/jpg fall back.

**Comment by p0psicles** [comment]
Ooh yes your right. I was looking at the wrong view.

**Pull request merged**
