### PR TITLE
Use unicode everywhere in list_associated_files() to fix PP issues

### PR DESCRIPTION
**Pull request by medariox**
Works perfectly fine for me so far.

@duramato @duramato @fernandog 
Would appreciate some testing.

### CODE REVIEW

**Comment by fernandog** [comment]
Testing this

**Comment by labrys** [comment]
And apparently @duramato should be checking this twice :)

**Comment by fernandog** [comment]
Approved

**Comment by medariox** [comment]
@labrys 
About things not do do... https://github.com/pymedusa/SickRage/blob/develop/SickBeard.py#L188 
That explains quite a few things, we should work on getting rid of that hack asap.

**Comment by medariox** [comment]
Will be included in the unicode branch when the time comes.

**Pull request closed without merging**
