### PR TITLE
Added 6box as a nn withoug caps, and moved the list to the init.

### PR DESCRIPTION
**Pull request by p0psicles**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

Notified 6box in forum, but doubt they will fix it.

### CODE REVIEW

**Comment by fernandog** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/pymedusa/SickRage/pull-request/829/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=pymedusa/SickRage)

**Comment by duramato** [comment]
UC can be removed? Think it's fixed..

**Comment by fernandog** [comment]
@p0psicles missing labels. Conclude or in progress?

**Comment by p0psicles** [comment]
Ooh sorry.  Concluded.

**Pull request merged**
