### PR TITLE
Adding S00EP00 pattern to guessit

### PR DESCRIPTION
**Pull request by ratoaq2**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

- To make @duramato happy with his "regular" cases :-)

### CODE REVIEW

**Comment by fernandog** [comment]
@duramato how many cases with SXXEPxx?

**Comment by duramato** [comment]
There are many french ones like so

**Comment by fernandog** [comment]
@duramato already tested this?

**Comment by fernandog** [comment]
@duramato worked?

**Comment by duramato** [comment]
Approved

**Pull request merged**
