### PR TITLE
Fix pymedusa/SickRage/issues/452

### PR DESCRIPTION
**Pull request by fernandog**
Fixes https://github.com/pymedusa/SickRage/issues/452
and 
Fixes https://github.com/pymedusa/SickRage/issues/453

### CODE REVIEW

**Comment by fernandog** [comment]
@medariox can you review please?

**Comment by medariox** [comment]
The first fix should be ok. About the second one, wouldn't it make more sense to check if the file exists before encoding child_path?
```
if ek(os.path.isfile, child_path):
    child_path_stat = ek(os.stat, child_path.encode(sickbeard.SYS_ENCODING))
    child_path_mode = stat.S_IMODE(child_path_stat[stat.ST_MODE])
    child_mode = fileBitFilter(parent_mode)
else:
    child_mode = parent_mode
```
Something like that.

**Comment by fernandog** [comment]
@medariox I did that before and I got this:

```python
            if ek(os.path.isfile, child_path):

                child_path_stat = ek(os.stat, child_path.encode(sickbeard.SYS_ENCODING))

                child_path_mode = stat.S_IMODE(child_path_stat[stat.ST_MODE])

                child_mode = fileBitFilter(parent_mode)

            else:

                child_mode = parent_mode

        except OSError as error:

            logger.warning(u'{error}', error=error)

            return

   
>       if child_path_mode == child_mode:

E       UnboundLocalError: local variable 'child_path_mode' referenced before assignment
```

https://travis-ci.org/pymedusa/SickRage/builds/154310616#L894

**Comment by medariox** [comment]
Bring it inside the if:
```
if ek(os.path.isfile, child_path):
    child_path_stat = ek(os.stat, child_path.encode(sickbeard.SYS_ENCODING))
    child_path_mode = stat.S_IMODE(child_path_stat[stat.ST_MODE])
    child_mode = fileBitFilter(parent_mode)
    if child_path_mode == child_mode:
        return
else:
    child_mode = parent_mode
```

**Comment by fernandog** [comment]
@medariox  we can't. `child_path_mode == child_mode` only if `isfile`. your code changes logic

**Pull request merged**
