### PR TITLE
Add setting: 'enable subliminal logs'. Default off

### PR DESCRIPTION
**Pull request by fernandog**
@ratoaq2 

use `sickbeard.SUBLIMINAL_LOG`

### CODE REVIEW

**Comment by fernandog** [comment]
@ratoaq2

This should be INFO.
I think we should patch subliminal. So we can choose levels instead of reduce level by 1

Also timestamp ia showing twice:

```
2016-04-07 17:44:01 17:44:01 WARNING::FINDSUBTITLES :: [1cf76ba] No results for episode
2016-04-07 17:43:45 17:43:45 WARNING::FINDSUBTITLES :: [1cf76ba] No results for series
2016-04-07 17:43:44 17:43:44 WARNING::FINDSUBTITLES :: [1cf76ba] No results for series
```

**Comment by ratoaq2** [comment]
Patching means changing all places all the time.
I have just added 1 commit to adjust some providers and refiners logging levels. That should be enough.

**Comment by medariox** [comment]
Approved

Looks good, I would say we try this and see how it turns out.

**Comment by fernandog** [comment]
its spamming a lot INFO
maybe we should only show WARNING/ERROR for subliminal

```
2016-04-08 07:45:03 INFO     FINDSUBTITLES :: [1cf76ba] Computed score 204 with final matches set(['episode', 'format', 'series', 'season', 'year', 'series_imdb_id', 'video_codec', 'resolution'])
2016-04-08 07:45:03 INFO     FINDSUBTITLES :: [1cf76ba] Computing score of  for video  with {'hearing_impaired': False}
2016-04-08 07:45:03 INFO     FINDSUBTITLES :: [1cf76ba] Computed score 202 with final matches set(['episode', 'format', 'series', 'season', 'year', 'series_imdb_id'])
2016-04-08 07:45:03 INFO     FINDSUBTITLES :: [1cf76ba] Computing score of  for video  with {'hearing_impaired': False}
2016-04-08 07:45:03 INFO     FINDSUBTITLES :: [1cf76ba] Computed score 204 with final matches set(['episode', 'format', 'series', 'season', 'year', 'series_imdb_id', 'video_codec', 'resolution'])
2016-04-08 07:45:02 INFO     FINDSUBTITLES :: [1cf76ba] Computing score of  for video  with {'hearing_impaired': False}
2016-04-08 07:45:02 INFO     FINDSUBTITLES :: [1cf76ba] Computed score 203 with final matches set(['episode', 'format', 'series', 'season', 'year', 'series_imdb_id', 'video_codec'])
2016-04-08 07:45:02 INFO     FINDSUBTITLES :: [1cf76ba] Computing score of  for video  with {'hearing_impaired': False}
2016-04-08 07:45:02 INFO     FINDSUBTITLES :: [1cf76ba] Computed score 202 with final matches set(['episode', 'format', 'series', 'season', 'year', 'series_imdb_id'])
2016-04-08 07:45:01 INFO     FINDSUBTITLES :: [1cf76ba] Computing score of  for video  with {'hearing_impaired': False}
2016-04-08 07:45:01 INFO     FINDSUBTITLES :: [1cf76ba] Computed score 204 with final matches set(['episode', 'format', 'series', 'season', 'year', 'series_imdb_id', 'video_codec', 'resolution'])
2016-04-08 07:45:01 INFO     FINDSUBTITLES :: [1cf76ba] Computing score of  for video  with {'hearing_impaired': False}
2016-04-08 07:45:01 INFO     FINDSUBTITLES :: [1cf76ba] Computed score 202 with final matches set(['episode', 'format', 'series', 'season', 'year', 'series_imdb_id'])
2016-04-08 07:45:01 INFO     FINDSUBTITLES :: [1cf76ba] Computing score of  for video  with {'hearing_impaired': False}
2016-04-08 07:45:01 INFO     FINDSUBTITLES :: [1cf76ba] Computed score 204 with final matches set(['episode', 'format', 'series', 'season', 'year', 'series_imdb_id', 'video_codec', 'resolution'])
2016-04-08 07:45:00 INFO     FINDSUBTITLES :: [1cf76ba] Computing score of  for video  with {'hearing_impaired': False}
2016-04-08 07:45:00 INFO     FINDSUBTITLES :: [1cf76ba] Computed score 203 with final matches set(['episode', 'format', 'series', 'season', 'year', 'series_imdb_id', 'video_codec'])
2016-04-08 07:45:00 INFO     FINDSUBTITLES :: [1cf76ba] Computing score of  for video  with {'hearing_impaired': False}
2016-04-08 07:45:00 INFO     FINDSUBTITLES :: [1cf76ba] Computed score 202 with final matches set(['episode', 'format', 'series', 'season', 'year', 'series_imdb_id'])
2016-04-08 07:44:59 INFO     FINDSUBTITLES :: [1cf76ba] Computing score of  for video  with {'hearing_impaired': False}
2016-04-08 07:44:54 INFO     FINDSUBTITLES :: [1cf76ba] Downloading archive 5706bc58f0153
```

**Pull request merged**
