### PR TITLE
Restructure

### PR DESCRIPTION
**Pull request by ratoaq2**
# IMPORTANT: DO NOT SQUASH COMMITS WHEN MERGING IT

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)
- [x] Renaming folder sickbeard -> medusa
- [x] Move code from sickrage -> medusa
- [x] Change sickbeard.PROPERTY to app.PROPERTY

### CODE REVIEW

**Comment by fernandog** [comment]
```
File /home/osmc/SickRage/gui/slick/views/status.mako:8, in render_content:
<%block name="content">
NameError: 'sickbeard' is not defined
```

**Comment by fernandog** [comment]
@OmgImAlexis what is this?

`core.js:        if (pyVar.match('sickbeard')) {`

**Comment by OmgImAlexis** [comment]
@fernandog please tell me you didn't change that js? That's for detecting meta values using `sickbeard.*` like `sickbeard.home_order`, etc.

**Comment by fernandog** [comment]
Yes ot was renamed to `medusa`. 
Isnt that for read medusa settings from config?

**Comment by OmgImAlexis** [comment]
It's for reading values from the meta tags but I think it can be removed anyways. I'll add a fix for all of this in a bit.

**Pull request merged**
