### PR TITLE
Open manual snatch href in new tab when clicked with shift, ctrl middle mouse button

### PR DESCRIPTION
**Pull request by p0psicles**
This will open the manual snatch link in a new tab/window when the link is clicked icw ctrl, shift or middle mouse button.

Pls don't mind the branch name. Something went wrong there.

### CODE REVIEW

**Comment by p0psicles** [comment]
fixes: https://github.com/pymedusa/SickRage/issues/170

**Comment by labrys** [comment]
@OmgImAlexis how does this look to you?

**Comment by OmgImAlexis** [comment]
Approved!

**Comment by labrys** [comment]
Approved!

**Pull request merged**
