### PR TITLE
Database updates

### PR DESCRIPTION
**Pull request by labrys**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Always make sure the PR has a clear description of why,how, and what your trying to fix. The same goes for improvements or new features. Also if you refering to an issue, make sure a summary is available in the PR.
- [ ] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

* Refactor mainDB to main_db
* Bump main_db version to 43.1
* Fix db backup not showing minor versions
* Add *.db to gitignore

### CODE REVIEW

**Comment by labrys** [comment]
#392

**Comment by p0psicles** [comment]
https://github.com/pymedusa/SickRage/issues/392

**Comment by labrys** [comment]
echo.... echo... echo..... :smile:

**Comment by p0psicles** [comment]
approved

**Pull request merged**
