### PR TITLE
Changed logic using check on searchThreads for manual episode searches

### PR DESCRIPTION
**Pull request by p0psicles**
Episode is no longer in search or queued thread AND results in cache table are newer then last found results, then refresh the page.

Following status are used:
finished: Search finished without results
refresh: Search finished with new results
queued: Episode obj is queued for manual search
searching: Episode obj is in manual search
idle: error with json send.

### CODE REVIEW

**Comment by p0psicles** [comment]
@pymedusa/developers pls review.

**Comment by duramato** [comment]
Perhaps add The loading icon next to the search is beeing performed text?

**Comment by p0psicles** [comment]
I think an icon is kind of trivial at this stage. Same can be said for the font size of the notification, color, spacing, etc.

**Comment by p0psicles** [comment]
Okay @labrys most of your comments have been implemented. Some parts have been rewritten. And some webserve related to manual search have been moved to manualsearch.py or search_queue.py.

Probably will leave some bugs.

**Pull request merged**
