### PR TITLE
Add footers to season tables

### PR DESCRIPTION
**Pull request by Thraxis**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

Add footers to season tables with information for each season.

* Num of episodes downloaded
* Total size of files for season

See Issue #575 for Request

image

### CODE REVIEW

**Comment by fernandog** [comment]
@Thraxis can you rebase please?

**Comment by fernandog** [comment]
Approved

**Comment by Thraxis** [comment]
Yes this has been tested with multiple seasons... and it is rebased

**Comment by fernandog** [comment]
@Thraxis can you rebase this please?

**Pull request merged**
