### PR TITLE
Add exception for ParseError. Fixes #1066

### LINKED ISSUE #1066: [APP SUBMITTED]: ParseError: unclosed token: line 104, column 12
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Commit**: PyMedusa/SickRage@c6c6e8412f45c591f4257bd4bceeca84261c2913
**Link to Log**: https://gist.github.com/390d7bed2edf3e1a87218df470c99203
### ERROR
<pre>
2016-09-10 04:37:02 ERROR    SHOWQUEUE-REFRESH :: [c6c6e84] 269750: Error while refreshing show Wayward Pines. Error: unclosed token: line 104, column 12
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/show_queue.py#L581">sickbeard/show_queue.py</a>", line 581, in run
    self.show.update_metadata()
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L547">sickbeard/tv.py</a>", line 547, in update_metadata
    self.__update_show_nfo()
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/tv.py#L555">sickbeard/tv.py</a>", line 555, in __update_show_nfo
    result = cur_provider.update_show_indexer_metadata(self) or result
  File "/home/home/SickRage/<a href="../blob/c6c6e8412f45c591f4257bd4bceeca84261c2913/sickbeard/metadata/generic.py#L273">sickbeard/metadata/generic.py</a>", line 273, in update_show_indexer_metadata
    showXML = etree.ElementTree(file=xmlFileObj)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 611, in __init__
    self.parse(file)
  File "<string>", line 38, in parse
ParseError: unclosed token: line 104, column 12
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by fernandog** [comment]
@medariox how do you know xml was invalid? Maybe is decore error

**Comment by medariox** [comment]
@fernandog 
Change the message to your liking.

**Comment by fernandog** [comment]
My point is: I think we are not fixing the root cause

**Comment by fernandog** [comment]
@medariox the exception was caused because we weren't using `encoding='utf8'` right?

**Comment by fernandog** [comment]
Approved

**Comment by fernandog** [comment]
Fixes https://github.com/pymedusa/SickRage/issues/484

**Pull request merged**
