### PR TITLE
replace gui dir with views & static

### PR DESCRIPTION
**Pull request by OmgImAlexis**
# ************** DO NOT MERGE **************

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
Can you guys test and then one of you review and merge. This can be squashed. If there's any conflicts then use the latest version of the files as this should only be moving files from the gui dir and then there's a few lines in some python files that needed to be updated.

**Comment by fernandog** [comment]
running this in my branch. seems good

**Comment by fernandog** [comment]
Im my local rebase I got this:

```
warning: CRLF will be replaced by LF in lib/babelfish/data/iso-3166-1.txt.
The file will have its original line endings in your working directory.
```

and 

```
<stdin>:494: trailing whitespace.
    <input type="hidden" id="is_priority" name="is_priority" value="0">
<stdin>:554: trailing whitespace.
                </table>
warning: 2 lines add whitespace errors.

```

**Comment by OmgImAlexis** [comment]
the lib dir shouldn't be affected at all..
@ratoaq2 can you have a look and merge if possible. I'm not 100% sure if this moved the files with git or if it moved just the old versions of them.. 😞

**Pull request merged**
