### PR TITLE
Change back ignored/required words log level to INFO

### PR DESCRIPTION
**Pull request by fernandog**
Added this so everybody could confirm new ignored/required code is working properly and to avoid  keeping looking at logs.
If you all say its working, merge this.

### CODE REVIEW

**Comment by p0psicles** [comment]
Approved

**Comment by fernandog** [comment]
@duramato @medariox @labrys is it working for you? no issues about required/ignored words?

**Comment by duramato** [comment]
Approved

**Comment by medariox** [comment]
Working fine here. I think this can be safely merged.

**Pull request merged**
