### PR TITLE
Update pull approve to include Thraxis

### PR DESCRIPTION
**Pull request by fernandog**
will only have effect when merged into master

@Thraxis 

No idea why it failed:
Parsing errors
  "{'required': 1, 'name': 'devs', 'members': ['duramato', 'fernandog', 'labrys', 'medariox', 'ratoaq2', 'p0psicles', 'OmgImAlexis', 'adaur', 'Thraxis']}" is an invalid value for reviewers: 'Thraxis' is not a collaborator of this repo

### CODE REVIEW

**Comment by fernandog** [comment]
@medariox know whats going on?

**Comment by medariox** [comment]
@fernandog 
No idea sadly.

**Comment by fernandog** [comment]
@p0psicles any clue?

**Comment by Thraxis** [comment]
Welll.. considering I wasn't on the PullApprove site before..

**Pull request merged**
