### PR TITLE
Moved old webapi to api/v1

### PR DESCRIPTION
**Pull request by OmgImAlexis**
For now I've moved the `core.py` for the webapi along with allowing `/api` and `/api/v1` to work as a single route. Eventually `/api` should be deprecated as the way it was written doesn't allow for REST routes and forces the API key to be added in the url path.

### CODE REVIEW

**Comment by fernandog** [comment]
@OmgImAlexis concluded? in progress?

**Comment by duramato** [comment]
Does this break backwards compability? i noticed you changed an api route to include v1

**Comment by OmgImAlexis** [comment]
@duramato it shouldn't since it allows `/api/{key}` as well as `/api/v1/{key}`.

**Comment by fernandog** [comment]
@OmgImAlexis third party apps will need to change to /api/v1/{key} or v1 is the default one?

**Comment by OmgImAlexis** [comment]
Both are currently active. I'd suggest we update as much of the docs to point to `/api/v1/{key}` as the new correct path as `/api/{key}` will be removed eventually as we transition to `/api/v2`.

For now calling either URL will work exactly the same, eventually once `/api/{key}` is removed the `/api` endpoint will simply return a status if the apiKey is valid and nothing else.

**Comment by OmgImAlexis** [comment]
@fernandog can this be merged?

**Comment by fernandog** [comment]
@p0psicles? @medariox?  Anything against?

**Comment by medariox** [comment]
Approved

**Comment by OmgImAlexis** [comment]
@medariox yes, I was waiting on this being merged first though since I wanted the directory structure to be corrected before I go adding it in. I'm also working on the [RAML code](http://raml.org/) for the two APIs

**Pull request merged**
