### PR TITLE
[Manual Snatch] Add "Manual Snatch" to Schedule page

### PR DESCRIPTION
**Pull request by fernandog**
@OmgImAlexis @p0psicles @duramato 

what is the reason for `  </a> `

looks like the `class="epManualSnatch"` is the most important thing isn't?

### CODE REVIEW

**Comment by p0psicles** [comment]
Is the snatch button only supposed to show for the list layout?

**Comment by fernandog** [comment]
I dont know how to add to others...

**Comment by p0psicles** [comment]
Ok, just merge this one. Then i'll ad the icons to the other layouts, and also add the core.min.js. Okay?

**Comment by fernandog** [comment]
@p0psicles everything ok with this code?

**Pull request merged**
