### PR TITLE
Fix pymedusa/SickRage/issues/540

### PR DESCRIPTION
**Pull request by fernandog**
Using the same "solution" found in home.mako

TODO:
- [x] Wrapping first text
- [x] Align text with object
- [x] Text doesn't fit object (also it seems its not inheriting font - guessing)

@p0psicles @OmgImAlexis 

- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Always make sure the PR has a clear description of why,how, and what your trying to fix. The same goes for improvements or new features. Also if you refering to an issue, make sure a summary is available in the PR.
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
@fernandog can you check again for me? Don't expect it to be the same as it was. Because i'm using a grid now, we can't stack the input's as a train after one another. But as one of the benifits of using grids, The behavior is much more predictable on different screen sizes. If you do want it like it was, that's possible, but will require allot of custom css.

**Comment by p0psicles** [comment]
Full Screen:
image

From about 1052 px:
image

From 768px:
image

**Comment by fernandog** [comment]
Approved

**Comment by p0psicles** [comment]
Approved

**Comment by p0psicles** [comment]
https://github.com/pymedusa/SickRage/issues/392

**Pull request merged**
