### PR TITLE
[Manual Search] Add provider setting 'Enable manual searches'

### PR DESCRIPTION
**Pull request by fernandog**
It will only use "manual search" providers when you use "Force results" button. Because this providers don't get updated in DailySearcher as they are manual search only

So its a mix of @duramato and mine (fallback)

- Fixes thread name while doing forced search
Before:
 [c352080] Performing episode search for 
After:
[MoreThanTV] :: [c352080] Performing episode search for 

- Fixed "forced search when no results" using backlog enabled providers (in manual_snatch.py we used to use daily). Now we use "enable_manualsearch"

- Fixed: search for propers only in backlog enabled providers

- Initialize provider even if no query to execute

This changes UI but nothing that will break angular @OmgImAlexis

### CODE REVIEW

**Comment by fernandog** [comment]
@labrys wont touch mako or webserve for now.

I don't want to break webserve checkbox. Want to test my code properly. Testing when changing too much stuff makes harder to debug

If this PR works ok then changes the try:except in webserve

**Comment by labrys** [comment]
@fernandog testing in process

**Comment by fernandog** [comment]
@labrys can you please commit your suggestion about loop providers  passing the type of active provider?

**Comment by fernandog** [comment]
Maybe add to helpers this function?

**Comment by labrys** [comment]
@fernandog sounds like a good idea, ill look at doing that later today.

**Comment by fernandog** [comment]
@labrys please review. finished

**Comment by labrys** [comment]
Approved

**Pull request merged**
