### PR TITLE
Fix saving config with non-ascii chars for None locale

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Always make sure the PR has a clear description of why,how, and what your trying to fix. The same goes for improvements or new features. Also if you refering to an issue, make sure a summary is available in the PR.
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
https://github.com/pymedusa/SickRage/issues/392

**Comment by labrys** [comment]
This fixes the issues with trying to save non-ascii characters to the config file (such as subs directories, etc).  Tested good for me with Win 10 and with None locale on linux for @medariox.

**Comment by medariox** [comment]
Approved

**Comment by labrys** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/pymedusa/SickRage/pull-request/595/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=pymedusa/SickRage)

**Pull request merged**
