### PR TITLE
[Manual Search] First call to snatchSelection always refreshed page with results

### PR DESCRIPTION
**Pull request by p0psicles**
The load() always handles the result, and replace the #container div with that. I've changed this to a $.getJson(), and only kicking the search to start. After this the container div is only refreshed when needed.

### CODE REVIEW

**Comment by p0psicles** [comment]
@duramato @fernandog Can you test this please?

**Comment by fernandog** [comment]
@p0psicles 
worked! thanks!
Can you make the spin wheel smaller to have the same height of the button?
Also disable the "force search" while search is running to avoid user click twice?

**Comment by fernandog** [comment]
Also fixes: https://github.com/pymedusa/SickRage/issues/252

**Comment by fernandog** [comment]
Approved

**Comment by fernandog** [comment]
rebased

**Comment by p0psicles** [comment]
Pls dont merge yet. Stil some weird behavior sometime. Need to test some more.

**Comment by p0psicles** [comment]
@OmgImAlexis?

**Comment by OmgImAlexis** [comment]
Looks fine to me.

**Pull request merged**
