### PR TITLE
Better search width and align

### PR DESCRIPTION
**Pull request by medariox**
After the change:
image

@pymedusa/contributors 
Looks good?

Some downsides of left alignment:
image

### CODE REVIEW

**Comment by fernandog** [comment]
@medariox 
i vote por center alignment.
if you hide some columns it gets really ugly the left alignment

**Comment by medariox** [comment]
I don't love the left alignment either. Both alignments have up- and downsides.

**Comment by labrys** [comment]
Personally i think centered looks terrible.  I think it should be 3 sub columns within search so that icons always appear in same column.  Also if forced search icons are hidden, why aren't selective also hidden?  lastly i think that CC should be moved to the left side so it appears closer to the subtitles and so that the selective search arrow appears to point "off the page" instead of at the cc.

**Comment by fernandog** [comment]
manual search/snatch shouldn't be hidden when status is skipped

**Comment by labrys** [comment]
imo if one method of file search is present the other should also be present.

**Comment by OmgImAlexis** [comment]
Why not just use `display:none;` or something similar and keep the icon there but just hide it from the user? That way they always stay in their spots and we don't need to add any extra columns.

**Comment by labrys** [comment]
@OmgImAlexis thats what i was thinking but my sleep-deprived mind couldnt quite dredge it out :)

**Comment by OmgImAlexis** [comment]
Also that icon may need to be changed as it is right now that looks like you're telling people that the search icon will do something called "CC" since it's pointing from one icon to the other.. :disappointed:

**Comment by medariox** [comment]
I like the idea of just hiding the image and also agree that we need a better "manual snatch" icon. This PR was aiming to be a quick fix for the current ugliness, further improvements will need a new PR. Going to merge the wider search column without left alignment for now, hope that's okay.

**Pull request closed without merging**
