### PR TITLE
Remaining Medusa rebrand

### PR DESCRIPTION
**Pull request by fernandog**
- [x] Remove SickRage logo in ui.notification

### CODE REVIEW

**Comment by labrys** [comment]
@OmgImAlexis Any idea where the notification icon is located?  Nearest i can guess is the base64 encoded string in `ajaxNotification.js`.  Also is it possible to make this a variable so its easier to change in the future?

**Comment by OmgImAlexis** [comment]
Yep that should be it, I've been meaning to change that to a imgur.com link or something for a while. I'm really not sure why we even use a base64 link since it causes so many issues with IDE's because of the line length.

**Comment by labrys** [comment]
@OmgImAlexis for now im using a favicon `srRoot + '/images/ico/favicon-120.png'`

**Comment by fernandog** [comment]
Approved

**Comment by fernandog** [comment]
need approval from @OmgImAlexis or @p0psicles

**Comment by p0psicles** [comment]
Approved

**Pull request merged**
