### PR TITLE
Add 'sub' and 'idx' to default allowed extensions

### PR DESCRIPTION
**Pull request by fernandog**

### CODE REVIEW

**Comment by duramato** [comment]
Why add .sub and not any of the other subtitle formats that exist out there? 
And now that i see it , why are `srr` and `sfv` even there?

**Comment by fernandog** [comment]
@duramato legacy from sickbeard

**Comment by fernandog** [comment]
@ratoaq2 @medariox thoughts?

**Comment by medariox** [comment]
Approved

**Pull request merged**
