### PR TITLE
Fix selects width. It should auto resize

### PR DESCRIPTION
**Pull request by fernandog**
image

@OmgImAlexis

### CODE REVIEW

**Comment by OmgImAlexis** [comment]
This is because of the stupid Bootstrap hack that was added like 4 years ago that I fixed..

**Comment by fernandog** [comment]
@OmgImAlexis so what should we do ?

**Comment by fernandog** [comment]
@OmgImAlexis approve or else?

**Comment by fernandog** [comment]
@OmgImAlexis please?

**Pull request merged**
