### PR TITLE
Improve Pretome provider

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

* Removed quote
* Fix seeders, leechers, size parsing
* Use try_int
* Remove useless code
* General cleanup
* Pep

### CODE REVIEW

**Comment by medariox** [comment]
@duramato 
Do you know any other broken/wrong parsing provider?

**Comment by fernandog** [comment]
Approved

**Comment by fernandog** [comment]
Fixes https://github.com/pymedusa/SickRage/issues/703

**Comment by fernandog** [comment]
Fixed https://github.com/pymedusa/SickRage/issues/1090

**Pull request merged**
