### PR TITLE
Delete non-proper snatch after snatch proper

### PR DESCRIPTION
**Pull request by fernandog**
@duramato what do you think?

I manually deleted file as there is no point seeding something that is non-proper (when proper available)

```
2016-08-31 09:16:31 DEBUG    FINDPROPERS :: [888ac0a] Found proper tags for Major.Crimes.S05E10.PROPER.720p.HDTV.x264-KILLERS[ettv]. Snatching as PROPER
2016-08-31 09:16:31 INFO     FINDPROPERS :: [888ac0a] Found a non-proper snatch in post-processor folder: Major.Crimes.S05E10.720p.HDTV.x264-FLEET
2016-08-31 09:16:31 INFO     FINDPROPERS :: [888ac0a] Deleted the non-proper snatch in post-processor folder: /media/SAMSUNG/media/downloaded/series/Major.Crimes.S05E10.720p.HDTV.x264-FLEET
```

any one see any improvement to this code?

### CODE REVIEW

**Comment by duramato** [comment]
You should always seed back.

**Comment by fernandog** [comment]
why seed something that was nuked?

**Comment by fernandog** [comment]
so create an option under proper settings?

**Comment by duramato** [comment]
Sure if you want to

**Pull request closed without merging**
