### PR TITLE
Fixing season special wrongly detected as season pack

### PR DESCRIPTION
**Pull request by ratoaq2**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

Discarding season specials (since it's not supported yet).

### CODE REVIEW

**Comment by p0psicles** [comment]
@ratoaq2, how am I supposed to test this? Can you help here?

**Comment by ratoaq2** [comment]
I think @duramato had a real use case.

The issue is when a release name is like:
`Show.Name.S02.Episode.Title.Special.720p.HDTV`

It was detecting season 2 and no episode number, therefore it was handling that as a season 2 pack.

If that release was snatched, then the whole season 2 was marked as snatched.

**Comment by fernandog** [comment]
@ratoaq2 , he is not going to test this because he is using another branch.

let's squash commit so he can 'git cherry-pick ......' in his current branch

**Comment by ratoaq2** [comment]
Rebased and squashed.
@duramato Now you can cherry pick it

**Comment by fernandog** [comment]
@duramato 

`git fetch origin`

`git cherry-pick db7fd81d48c6b77ed821ad0939eaf33db9385c31`

**Comment by fernandog** [comment]
@ratoaq2 did you tested? If so lets merge

**Comment by duramato** [comment]
Not fixed. They are still getting cached for S02.

https://gist.github.com/duramato/9d07446941169861bdb2be9c1ccce99c

**Comment by ratoaq2** [comment]
@duramato Fixed and rebased

**Comment by fernandog** [comment]
@duramato did it worked?

**Comment by duramato** [comment]
Approved

[Approved with PullApprove](https://pullapprove.com/pymedusa/SickRage/pull-request/784/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=pymedusa/SickRage)

**Pull request merged**
