### PR TITLE
Don't call clear_non_release_groups for non media files

### PR DESCRIPTION
**Pull request by fernandog**
@ratoaq2 also you weren't passing full path creating error:

`Couldn't remove non release groups from video file. Error: error 2 : The system cannot find the file specified`

@medariox

### CODE REVIEW

**Comment by medariox** [comment]
os.path.join() is used later. Where do you get this error?

**Comment by fernandog** [comment]
In function `clear_non_release_groups`

**Comment by medariox** [comment]
https://github.com/pymedusa/SickRage/blob/d93ebc45225eecd5c4b7e63420d308ce88d0ef10/sickbeard/subtitles.py#L726-L733

```
filename = clear_non_release_groups(os.path.join(root, filename))

if processTV.subtitles_enabled(filename) is False:
                    logger.debug(u'Subtitle disabled for show: %s', filename)
                    continue

video_path = os.path.join(root, filename)
release_name = os.path.splitext(filename)[0]
```

IIrc processTV.subtitles_enabled() needs just the file name, not the full path.

Join is repeated here: video_path = os.path.join(root, filename)
Also look at os.path.splitext(filename)[0], are you sure that filename can be safely a path, instead of a file name?

**Comment by fernandog** [comment]
Will say again: Look a the function code. It does a os.rename. without path = error.

**Comment by medariox** [comment]
It is obviously not a proper solution if it adds other issues.

**Comment by fernandog** [comment]
Np. Let's wait @ratoaq2 proper fix

**Comment by fernandog** [comment]
@medariox will this be merged? i've tested since your commits and no issues

**Comment by medariox** [comment]
Approved

**Comment by fernandog** [comment]
@pymedusa/developers someone merge please

**Comment by p0psicles** [comment]
Approved

**Pull request merged**
