### PR TITLE
Disable PP wrapper, since it makes NzbToMedia to not function properly

### PR DESCRIPTION
**Pull request by duramato**
- [ ] PR is based on the DEVELOP branch
- [ ] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [ ] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

### CODE REVIEW

**Comment by p0psicles** [comment]
Let's hold off this PR for now. Things i want to look into are queuing of the PP jobs.
I think we should implement this. IMO we have the following solution alternatives:

1. Implement queuing in Medusa. nzbToMedia will deliver a job with medusa, it's queued, and we need to create some sort of callback to nzbToMedia, to update it's db.
2. Implement queing in nzbToMedia, and make it send jobs to medusa synchronous.
3. Integrate nzbToMedia in medusa, and let download client communicate directly with medusa. This will be sort of a solution like number, with the difference that we won't need to make callbacks.

@pymedusa/developers what do you guys think?

**Comment by fernandog** [comment]
@duramato @p0psicles 
merge or not to merge?

**Comment by p0psicles** [comment]
sure merge it. To much trouble to really properly test now anyway.

**Comment by p0psicles** [comment]
Approved!

**Pull request merged**
