### PR TITLE
Fix adding new show

### PR DESCRIPTION
**Pull request by fernandog**
@medariox @Thraxis cant find out from where this come from....

### CODE REVIEW

**Comment by Thraxis** [comment]
That was supposed to be building the black and white list for anime release groups so you could set those when adding an Anime show.

**Comment by fernandog** [comment]
So confirm removal or need to add more code?

**Comment by Thraxis** [comment]
All the code for it should already be there in gui/slick/js/blackwhite.js

The call is in gui/slick/views/addShows_newShow.mako

**Comment by Thraxis** [comment]
I'm not seeing any problem that code in the current dev.

Below is the Black / Whitelist selector on the third step of adding a new show for "Highschool of the Dead" shortly after selecting "Is Anime" the list populates, of you have the anidb settings enabled in your config.

image

**Comment by fernandog** [comment]
But if anime is disabled, it will never populate right? I still cant add

**Comment by Thraxis** [comment]
Is this on the develop branch?  or another branch?  Is there an error generated?

**Comment by fernandog** [comment]
Im using my branch with some PR addes like yours

referenceError: generateBlackWhiteList is not defined

**Comment by Thraxis** [comment]
The function is defined in : https://github.com/pymedusa/SickRage/blob/master/gui/slick/js/blackwhite.js

The call to that JS file is in gui/slick/views/addShows_newShow.mako

https://github.com/pymedusa/SickRage/blob/19383871bc74d30648dbc44c239fd98e7830675a/gui/slick/views/addShows_newShow.mako#L10

**Comment by Thraxis** [comment]
Looks like it comes from the Recommended Shows update PR (#501) will see if p0psicles will chime in there about it.

**Pull request closed without merging**
