### PR TITLE
Fix TypeError: 'NoneType' object is not iterable

### PR DESCRIPTION
**Pull request by fernandog**
when can't check remote branches

### CODE REVIEW

**Comment by ratoaq2** [comment]
Approved

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Commit**: PyMedusa/SickRage@9b461cdcdb3f9c16e446475c9272dcd466d7f6aa
**Link to Log**: https://gist.github.com/631c6f24ef5c3608b90beba737708e0e
### ERROR
<pre>
2016-09-14 08:43:04 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Zooqle] :: [9b461cd] Error while searching Zooqle, skipping: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/9b461cdcdb3f9c16e446475c9272dcd466d7f6aa/sickbeard/search.py#L446">sickbeard/search.py</a>", line 446, in searchForNeededEpisodes
    curFoundResults = cur_provider.search_rss(episodes)
  File "/home/home/SickRage/<a href="../blob/9b461cdcdb3f9c16e446475c9272dcd466d7f6aa/sickrage/providers/GenericProvider.py#L409">sickrage/providers/GenericProvider.py</a>", line 409, in search_rss
    return self.cache.findNeededEpisodes(episodes)
  File "/home/home/SickRage/<a href="../blob/9b461cdcdb3f9c16e446475c9272dcd466d7f6aa/sickbeard/tvcache.py#L443">sickbeard/tvcache.py</a>", line 443, in findNeededEpisodes
    sql_results = list(itertools.chain(*sql_results))
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Commit**: PyMedusa/SickRage@9b461cdcdb3f9c16e446475c9272dcd466d7f6aa
**Link to Log**: https://gist.github.com/783f6af1c5854973f8316ba36b2daf90
### ERROR
<pre>
2016-09-14 06:31:52 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [T411] :: [9b461cd] Error while searching T411, skipping: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/9b461cdcdb3f9c16e446475c9272dcd466d7f6aa/sickbeard/search.py#L446">sickbeard/search.py</a>", line 446, in searchForNeededEpisodes
    curFoundResults = cur_provider.search_rss(episodes)
  File "/home/home/SickRage/<a href="../blob/9b461cdcdb3f9c16e446475c9272dcd466d7f6aa/sickrage/providers/GenericProvider.py#L409">sickrage/providers/GenericProvider.py</a>", line 409, in search_rss
    return self.cache.findNeededEpisodes(episodes)
  File "/home/home/SickRage/<a href="../blob/9b461cdcdb3f9c16e446475c9272dcd466d7f6aa/sickbeard/tvcache.py#L443">sickbeard/tvcache.py</a>", line 443, in findNeededEpisodes
    sql_results = list(itertools.chain(*sql_results))
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Comment by fernandog** [comment]
@ratoaq2 issue submitter is submitting in the PR

**Comment by duramato** [comment]
### INFO
**Python Version**: `2.7.6 (default, Jun 22 2015, 18:00:18) [GCC 4.8.2]`
**Operating System**: `Linux-4.2.0-42-generic-i686-with-Ubuntu-14.04-trusty`
**Locale**: `None`
**Branch**: [develop](../tree/develop)
**Database**: `44.2`
**Commit**: pymedusa/SickRage@baa22c5c1c14202addb11ab63a7b3f91c7e41778
**Link to Log**: https://gist.github.com/bb79baadefa2573523fc5ad3aec1aa2d
### ERROR
<pre>
2016-09-25 05:17:32 ERROR    SEARCHQUEUE-DAILY-SEARCH :: [Nutech] :: [baa22c5] Error while searching Nutech, skipping: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/home/home/SickRage/<a href="../blob/baa22c5c1c14202addb11ab63a7b3f91c7e41778/medusa/search/core.py#L445">medusa/search/core.py</a>", line 445, in searchForNeededEpisodes
    curFoundResults = cur_provider.search_rss(episodes)
  File "/home/home/SickRage/<a href="../blob/baa22c5c1c14202addb11ab63a7b3f91c7e41778/medusa/providers/GenericProvider.py#L408">medusa/providers/GenericProvider.py</a>", line 408, in search_rss
    return self.cache.findNeededEpisodes(episodes)
  File "/home/home/SickRage/<a href="../blob/baa22c5c1c14202addb11ab63a7b3f91c7e41778/medusa/tvcache.py#L442">medusa/tvcache.py</a>", line 442, in findNeededEpisodes
    sql_results = list(itertools.chain(*sql_results))
TypeError: 'NoneType' object is not iterable
</pre>
---
_STAFF NOTIFIED_: @pymedusa/support @pymedusa/moderators

**Pull request merged**
