### PR TITLE
Added icons M, D and B as indicators for provider abilities

### PR DESCRIPTION
**Pull request by p0psicles**
TODO:
- [ ] I only created the icons for dark theme. Didn't notice light theme used different color lock/unlock icons. So i'll have to create additonal icons, and adjust css.

- [x] Fixed some bugs that got recently introduced while changing exception handling on saving of providers.

### CODE REVIEW

**Comment by fernandog** [comment]
@p0psicles lol
image

**Comment by p0psicles** [comment]
You want to use these images? Then dont forget to adjust the margins. Personally im not really fond of them.

**Comment by fernandog** [comment]
Nope. Dod just for fun

**Comment by duramato** [comment]
image

**Comment by p0psicles** [comment]
How does it look with light theme?

**Comment by fernandog** [comment]
@p0psicles see second post. My SS

**Comment by p0psicles** [comment]
Okay, but I guess you fixed the margins after right?

**Comment by p0psicles** [comment]
Approved!

**Comment by fernandog** [comment]
https://github.com/pymedusa/SickRage/issues/199

**Comment by OmgImAlexis** [comment]
Why are they all using `!important`?

**Pull request merged**
