### PR TITLE
Fixing show refresh not happening anymore

### PR DESCRIPTION
**Pull request by ratoaq2**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)
- [x] Fixing show refresh not happening anymore
- [x] Making sure TVEpisode is not dirty after loading/saving from/to database.

### CODE REVIEW

**Comment by fernandog** [comment]
@ratoaq2 what do you think?

**Comment by ratoaq2** [comment]
The code change is fine and it shows that the force flag in QueueItemUpdate and QueueItemForceUpdate is useless (not used in any place). So QueueItemForceUpdate and QueueItemUpdate can be merged to a single class.

The commit comment is not accurate. Manual is indeed forced. But forced doesn't  mean manual. That's why the flag is called forced and not manual.

**Comment by fernandog** [comment]
in mass update, user can force a refresh but not a update. also in show page user can hit "re-scan" files only, so it shouldn't be a one class for both

but when user hit "force update" it will also do a re-scan (show refresh)

**Comment by fernandog** [comment]
Approved

**Pull request merged**
