### PR TITLE
Added cfscrape and js2py, added CF bypass in getURL, reordered imports

### PR DESCRIPTION
**Pull request by medariox**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

This is a first attempt to bypass CloadFlare's anti-bot protection with the help of cfscrape. It should already be quite stable. Adds two small libraries.

Todos:
- [x] Don't overwite the header
- [x] Make code nicer

Suggestions/Ideas are very welcome.

### CODE REVIEW

**Comment by duramato** [comment]
One thing tbn is that we will probably need to update that lib frequently as CF changes their anti bot

**Comment by medariox** [comment]
Yeah, we have to keep a close eye on cfscrape. Althought the author writes "once a year", I expect CF changes to happen more often: https://github.com/Anorov/cloudflare-scrape#updates
Anyway, the providers behind CF currently don't work at all, so either we bypass the protection, or we get rid of them (I prefer the first option).

**Comment by medariox** [comment]
Is there any interest in the PR? Not sure if it's worth it. Opinions?

**Comment by fernandog** [comment]
which providers will use it?

**Comment by duramato** [comment]
Currently torrentz and torrentproject but it can be used for other. There are many that use CF it's a matter of them turning security mode up and you can't use it without this.

**Comment by fernandog** [comment]
its is working, merge it then

**Comment by fernandog** [comment]
rebased. still in progress?

**Comment by fernandog** [comment]
torrentz2 working for me

**Comment by medariox** [comment]
@fernandog 
Yes, I'm not really satisfied with the code yet, but it works good.

**Comment by ratoaq2** [comment]
Approved

**Comment by fernandog** [comment]
@medariox 

got this only running medusa in command line:

2016-09-15 09:03:10 DEBUG    SEARCHQUEUE-MANUAL-250487 :: [TorrentProject] :: [5df34eb] CloudFlare protection detected, trying to bypass it
/home/osmc/SickRage/lib/js2py/constructors/time_helpers.py:9: Warning: Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time
  warnings.warn('Please install or fix tzlocal library (pip install tzlocal) in order to make Date object work better. Otherwise I will assume DST is in effect all the time', Warning)

**Comment by medariox** [comment]
@fernandog 
Like the warning states: either install tzlocal, or live with the message. It's an optional library.

**Pull request merged**
