### PR TITLE
Clean up properFinder

### PR DESCRIPTION
**Pull request by fernandog**

### CODE REVIEW

**Comment by fernandog** [comment]
@labrys please make other PR for all those changes.
This is a quick fix to beta/master

**Comment by fernandog** [comment]
Why wasnt merged to master? It will spam user log

**Comment by labrys** [comment]
Why wasn't it merged to master? `Needs review` `Needs testing`

**Comment by labrys** [comment]
Minor clean up for properFinder

**Comment by labrys** [comment]
Approved

**Pull request merged**
