### PR TITLE
Remove simplejson

### PR DESCRIPTION
**Pull request by labrys**
- [x] PR is based on the DEVELOP branch
- [x] Don't send big changes all at once. Split up big PRs into multiple smaller PRs that are easier to manage and review
- [x] Always make sure the PR has a clear description of why,how, and what your trying to fix. The same goes for improvements or new features. Also if you refering to an issue, make sure a summary is available in the PR.
- [x] Read [contribution guide](https://github.com/PyMedusa/SickRage/blob/master/.github/CONTRIBUTING.md)

As we require python 2.7+, and json is part of the standard libs, there is no need to import simplejson.  In addition simplejson has some unicode issues that may present problems such as this one:
https://code.google.com/archive/p/simplejson/issues/40

### CODE REVIEW

**Comment by p0psicles** [comment]
As discussed with @labrys we need to make this change somewhere. If we notice there are still systems that do not have json installed, and dpend on simplejson, we should make a decission, to revert it, or officially drop support for simplejson.

**Comment by p0psicles** [comment]
Approved

**Comment by medariox** [comment]
Approved

**Comment by labrys** [comment]
QC issues are existing issues and will be dealt with as part of the web server modularization.

**Pull request merged**
